# Generated by Django 3.0.1 on 2020-10-31 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('MENTOR', 'Mentor'), ('STUDENT', 'Student')], default='MENTOR', max_length=7),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='language',
            field=models.CharField(choices=[('ENGLISH', 'English'), ('SPANISH', 'Spanish')], default='ENGLISH', max_length=7),
        ),
    ]
